if has('win32')
    set guifont=Hack_Nerd_Font_Mono:h12,Consolas:h12
    set guifontwide=MS_Gothic:h13
    set linespace=0
    set renderoptions=type:directx,renmode:6

    augroup gvimrc
        autocmd!
        autocmd GUIEnter * simalt ~x
    augroup END
endif
